services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # - "3000:3000"
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - data

  ai:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "src/pipeline/init_collections.py"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/config:/app/config
      - ./data:/app/data
    depends_on:
      - data

  data:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma

  evaluation:
    build:
      context: ./evaluation
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./evaluation:/app
    depends_on:
      - data
      - backend
    networks:
      - default

volumes:
  chroma-data:

networks:
  default:
    driver: bridge
